ALTER TABLE `%PRE%user_packs` CHANGE `id` `id` MEDIUMINT( 9 ) UNSIGNED NOT NULL AUTO_INCREMENT, CHANGE `userid` `userid` MEDIUMINT( 9 ) UNSIGNED NOT NULL;
DELETE FROM `%PRE%config` WHERE `name` = 'smtp_user' LIMIT 1;
DELETE FROM `%PRE%config` WHERE `name` = 'senabled' LIMIT 1;
ALTER TABLE `%PRE%config` ADD PRIMARY KEY(`name`);
UPDATE `%PRE%config` SET `name` = 'vname' WHERE `name` = 'version' LIMIT 1;
INSERT INTO `%PRE%config` (`name`, `value`) VALUES ('vcode', '1010204');
INSERT INTO `%PRE%config` (`name`, `value`) VALUES ('timezone', 'UTC');
ALTER TABLE `%PRE%servers` CHANGE `name` `name` VARCHAR(75) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `host` `host` VARCHAR(75) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `user` `user` VARCHAR(75) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
INSERT INTO `%PRE%config` (`name`, `value`) VALUES ('wwwsubdomain', 'both');
INSERT INTO `%PRE%config` (`name` ,`value`) VALUES ('smtp_port',  '25'), ('smtp_secure',  '0');
INSERT INTO `%PRE%config` (`name`, `value`) VALUES ('emailval', '1');
ALTER TABLE `%PRE%users` ADD `emailval` BOOLEAN NOT NULL DEFAULT '0';
INSERT INTO `%PRE%templates` (`id`, `name`, `acpvisual`, `subject`, `content`, `description`) VALUES
	(NULL, 'newaccval', 'New Hosting Account + Email Confirmation', 'Your Hosting Account', '<p><span style="font-weight: bold;">Your account has been created!<br /><span style="font-weight: normal;">Your account has been successfully created and you''re now able to log into your client control panel and your web hosting control panel. Your details are as follows:</span></span></p><p><span style="font-weight: bold;">Username: </span>%USER%<br /><span style="font-weight: bold;">Password: </span>%PASS%<br /><span style="font-weight: bold;">Email: </span>%EMAIL%<br /><span style="font-weight: bold;">Domain/Subdomain: </span>%DOMAIN%<br /><span style="font-weight: bold;">Package: </span>%PACKAGE%<br /><span style="font-weight: bold;">Confirmation Link: </span><a title="Confirmation Link" href="%CONFIRM%">%CONFIRM%</a></p>', 'This is the email a client gets when they first go though the order form and complete it. This email should contain all their details.<br /><br />Template Variables:<br />%USER% - Client Username<br />%PASS% - Client Password<br />%EMAIL% - Client Email<br />%DOMAIN% - The clients package url<br />%PACKAGE% - The package the client signed up for<br />%CONFIRM% - The confirmation link'),
	(NULL, 'emailconfirm', 'Email Confirmation', 'Please Confirm Your Email', '<p><strong>%USER%,</strong><br />Please confirm the email address associated with your hosting account by clicking the link below.</p><p><a href="%CONFIRM%">%CONFIRM%</a></p>', 'This is the email the user receives if they ask for another confirmation email, they change their email, or an admin requests email verification for that account.<br /><br />Template Variables:<br />%USER% - Client username<br />%CONFIRM% - The confirmation link'),
	(NULL, 'newaccadminval', 'Awaiting Validation + Email Confirmation', 'Awaiting Admin Validation', '<p><span style="font-weight: bold;">Your account is awaiting admin validation!<br /><span style="font-weight: normal;">Your account has been successfully created but you need to wait for an admin to approve your account! You''re now able to log into your client control panel. Your details are as follows:</span></span></p><p><span style="font-weight: bold;">Username:&nbsp;</span>%USER%<br /><span style="font-weight: bold;">Password:&nbsp;</span>%PASS%<br /><span style="font-weight: bold;">Email:&nbsp;</span>%EMAIL%<br /><span style="font-weight: bold;">Domain/Subdomain:&nbsp;</span>%DOMAIN%<br /><span style="font-weight: bold;">Package:&nbsp;</span>%PACKAGE%<br /><span style="font-weight: bold;">Confirmation Link: </span><a title="Confirmation Link" href="%CONFIRM%">%CONFIRM%</a>', 'This is the email a client gets when they first go though the order form and complete it but are awaiting the admin. This email should contain all their details. This will only be sent if email confirmation is enabled.<br /><br />Template Variables:<br />%USER% - Client Username<br />%PASS% - Client Password<br />%EMAIL% - Client Email<br />%DOMAIN% - The clients package url<br />%PACKAGE% - The package the client signed up for<br />%CONFIRM% - The confirmation link');
UPDATE `%PRE%templates` SET `description` = 'This is the email a client gets when they first go though the order form and complete it but are awaiting the admin. This email should contain all their details. This will only be sent if email confirmation is disabled.<br /><br />Template Variables:<br />%USER% - Client Username<br />%PASS% - Client Password<br />%EMAIL% - Client Email<br />%DOMAIN% - The clients package url<br />%PACKAGE% - The package the client signed up for' WHERE `id` = 7;
UPDATE `%PRE%templates` SET `description` = 'This is the email a client gets when they first go though the order form and complete it. This email should contain all their details.<br /><br />Template Variables:<br />%USER% - Client Username<br />%PASS% - Client Password<br />%EMAIL% - Client Email<br />%DOMAIN% - The clients package url<br />%PACKAGE% - The package the client signed up for' WHERE `id` = 3;
ALTER TABLE `%PRE%users` ADD `confirmcode` VARCHAR(40) NULL DEFAULT NULL,  ADD `newemail` VARCHAR(50) NULL DEFAULT NULL;
ALTER TABLE `%PRE%clientnav` ADD `weight` INT NOT NULL;
UPDATE `%PRE%clientnav` SET `weight` = '-100' WHERE `id` = 1;
UPDATE `%PRE%clientnav` SET `weight` = '1' WHERE `id` = 3;
UPDATE `%PRE%clientnav` SET `weight` = '15' WHERE `id` = 4;
UPDATE `%PRE%clientnav` SET `weight` = '30' WHERE `id` = 5;
UPDATE `%PRE%clientnav` SET `weight` = '100' WHERE `id` = 2;
UPDATE `%PRE%clientnav` SET `weight` = '45' WHERE `id` = 7;
UPDATE `%PRE%clientnav` SET `weight` = '60' WHERE `id` = 8;
INSERT INTO `%PRE%clientnav` (`id`, `visual`, `icon`, `link`, `weight`) VALUES (NULL, 'Change Email', 'email_edit.png', 'email', '31');